version: '2'
services:
  spark-master:
    build: .
    command: /usr/local/bootstrap.sh master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - SPARK_MASTER_HOST=spark-master
  spark-worker:
    build: .
    command: /usr/local/bootstrap.sh worker
    ports:
      - "8081:8081"
      - "4040:4040"
    links:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
        
